package com.hardi.noteservice.domain

import org.bson.types.ObjectId
import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document
import java.time.Instant

@Document("notes")
data class Note(
    //id generated by mongoDB (mongoDB specific type)
    //It also contains timestamp
    @Id
    val id: ObjectId?,

    val title: String,
    val content: String,
    val color: String,
    val createdAt: Instant,
    val ownerId: ObjectId
)
